services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=John
      - POSTGRES_DB=relationshipTesting
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=johnb08.kodehode@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data: