services:
  client:
    build: 
      context: ./client/React-Bedrifttracker-prototype
      dockerfile: dockerfile
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: ./client/React-Bedrifttracker-prototype
          target: /src/
          ignore:
            - node_modules
        - action: rebuild
          path: ./client/React-Bedrifttracker-prototype/package.json
  server: 
    image: node:20-bookworm-slim
    command: ["node", "./app/server.js"]
    ports:
      - 3000:3000
    volumes:
      - ./server:/app/
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=John
      - POSTGRES_DB=relationshipTesting
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=johnb08.kodehode@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data: