export const economicCodes = {
    ADI:	"Annen driftsinntekt",
    ADK:	"Andre driftskostnader",
    AEK:	"Annen egenkapital",
    AEKK:	"Udekket tap",
    AFA:	"Andre finansielle anleggsmidler",
    AFI:	"Andre finansinntekter",
    AFK:	"Sum andre finanskostnader",
    AFKK: 	"Andre finanskostnader",
    AFM: 	"Andre finansielle instrumenter", 
    AFV: 	"Avsetning fond for vurderingsforskjeller",
    AID: 	"Aksjer/Investeringer i datterselskap",
    AIM:	"Andre immatrielle eiendeler",
    AIV:	"Andre investeringer",
    AK:	    "Aksjekapital/andelskapital/selskapskapital",
    AKG:	"Annen kortsiktig gjeld",
    AKR:	"Andre kreditorer",
    AKSB:	"Aksjonærbidrag",
    ALG:	"Annen langsiktig gjeld",
    ALK:	"Ansvarlig lånekapital",
    AMF:	"Andre markedsbaserte finansielle instr.",
    ANDLØ:	"Leder annen godtgjørelse",
    ANF:	"Andre fordringer",
    ANFF:	"Andre finansielle fordringer",
    ANIE:	"Annen innskutt egenkapital",
    ANLG:	"Annen langsiktig gjeld",
    ANT:	"Ansatte fra regnskap",
    AOM:	"Andre omløpsmidler",
    ARI:	"Andre renteinntekt",
    ARK:	"Andre rentekostnader",
    ARKA:	"Arbeidskapital",
    AV:	    "Andre varer",
    AVD:	"Andre varige driftsmidler",
    AVS:	"Andre avsetninger for forpliktelser",
    AVUB:	"Avsatt utbytte",
    BE:	    "Beholdningsendringer",
    BEE:	"Beholdningsendringer egentilvirkede varer",
    BEEA:	"Beholdningsendring av egentilvirkede anleggsmidler",
    BET:	"Beholdningsendringer ferdig tilvirkede varer",
    BF:	    "Bruttofortjeneste i %",
    BS:	    "Betalbar skatt",
    Currency:	"Valuta",
    DR:	    "Driftsresultat",
    EB:	    "Tomter, bygninger og annen fast eiendom",
    EBEF:	"Endring i beholdning av egentilvirkede og ferdige varer",
    EBITDA:	"Inntjening før renter, skatt, avskrivninger og nedskrivninger",
    EGA: 	"Egne aksjer",
    EI: 	"Ekstraordinære inntekter",
    EK: 	"Ekstraordinære kostnader",
    EKA:	"Egenkapitalandel i % (Også kalt soliditet)",
    EKAVO:	"Egenkapitalens andel av omsetning",
    ER: 	"Egenkapital rentabilitet før skatt i %",
    ERE:	"Egenkapital rentabilitet etter skatt i %",
    FDS:	"Konsernfordringer",
    FFFO:	"Fond",
    FFUG:	"Fond for urealiserte gevinster",
    FFV:	"Fond for vurderingsforskjeller",
    FG1:	"Finansieringsgrad I",
    FI: 	"Finansinntekter",
    FK: 	"Finanskostnader",
    FONE:	"Fondsemisjon",
    FOU:	"Forskning og utvikling",
    GG: 	"Gjeldsgrad",
    GLA:	"Goodwill",
    GTD:	"Langsiktig konserngjeld",
    GTI:	"Gjeld til kredittinstitusjoner",
    GTS:	"Garantistillelser",
    HUSLK:	"Husleiekostander",
    IFS:	"Investeringer i annet foretak i samme konsern",
    IPA:	"Inntekt på investering i annet foretak i samme konsern",
    IPI:	"Inntekt på investering i datterselskap",
    IPT:	"Inntekt på investering i tilknyttet selskap",
    IRK:	"Annen innskutt egenkapital",
    ITS:	"Investeringer i tilknyttet selskap",
    IVEI:	"Investeringseiendom",
    IAA:	"Investeringer i aksjer og andeler",
    KB: 	"Konsernbidrag",
    KBP:	"Kontanter/bank/post",
    KBPS:	"Sum Kasse/Bank/Post",
    KGA:	"Kortsiktig gjeldsandel i %",
    KL: 	"Konvertible lån",
    KLON:	"Herav lønn- og feriepenger",
    KOH:	"Kapitalens omløpshastighet", 
    KPL:	"Konsesjoner/patenter/lisenser/varemerker/og lignende rettigheter",
    KSK:	"Krav på innbetaling av selskapskapital",
    KSL:	"Sertifikatlån",
    KUF:	"Kundefordringer",
    KVL:	"Konvertible lån",
    LEDPS:	"Leder pensjonskostnad",
    LFK:	"Lån til foretak i samme konsern",
    LG: 	"Leverandørgjeld",
    LGA:	"Langsiktig gjeldsandel i %",
    LGR:	"Likviditetsgrad I",
    LGR2:	"Likviditetsgrad II",
    LGR3:	"Likviditetsgrad III",
    LI: 	"Leieinntekter",
    LIMKA:	"Kassekreditt LIMIT",
    LL: 	"Lederlønn (i hele kroner)",
    LLF:	"Langsiktig lagerfinansiering i %",
    LT: 	"Lagertid i ant. dager",
    LTK:	"Lån til tilknyttet selskap og felles kontrollert virksomhet",
    LTP:	"Lønn/trygd/pensjon",
    MA: 	"Minoritetens andel før årsresultat",
    MAK:	"Markedsbaserte aksjer",
    MAO:	"Markedsbaserte obligasjoner",
    MAS:	"Kortsiktig konserngjeld",
    MI: 	"Driftsløsøre/inventar/verktøy/biler",
    MIN:	"Minoritetsinteresser",
    MINK:	"Minoritet etter opptj.e.kapital",
    MOA:	"Maskiner og anlegg",
    MU: 	"Mottatt utbytte",
    NE: 	"Netto ekstraordinær inntekt",
    NF: 	"Netto finans",
    NFA:	"Nedskriving finansielle anleggsmidler",
    NFO:	"Nedskriving av andre finansielle omløpsmidler",
    NVD:	"Nedskriving av varige driftsmidler/immaterielle eiendeler",
    OAE:	"Overføringer til/fra annen egenkapital",
    OAEE:	"Udekket tap",
    OBL:	"Obligasjonslån",
    OBLG:	"Obligasjoner",
    OBLNM:	"Obligatorisk tjenestepensjon",
    OFA:	"Offentlige avgifter",
    OFUG:	"Overføring til/fra fond for urealiserte gevinster",
    OG: 	"Overskuddsgrad i %",
    OKF:	"Overkursfond",
    OOF:	"Obligasjoner og andre fordringer",
    OOF3:	"Andre fordringer",
    OPA:	"Omsetning/ansatt (hele 1000)",
    OPAV:	"Omsetning per årsverk",
    OPLK:	"Omsetning/lønnskrone",
    OR: 	"Ordinært resultat",
    ORA:	"Ordinære avskrivninger",
    ORS:	"Ordinært resultat før skattekostnad",
    OTFF:	"Overføring til/fra fond",
    PF: 	"Pensjonsforpliktelser",
    PG: 	"Pantegjeld/gjeld til kredittinstitusjoner",
    PNKO:	"Pensjonskostnader",
    PSM:   	"Pensjonsmidler",
    PST:	"Pantstillelser",
    RDG:	"Rentedekningsgrad i %",
    REVAN:	"Annen revisjonsbistand",
    REVHO:	"Revisjonshonorar (i hele kroner)",
    RFF:	"Renteinntekter fra foretak i samme konsern",
    RG: 	"Resultat av driften i %",
    RTK:	"Renter til konsern",
    SAM:	"Sum anleggsmidler",
    SAP:	"Sum avsetninger til forpliktelser",
    SDI:	"Sum driftsinntekter",
    SDK:	"Sum driftskostnader",
    SED:	"Sum eiendeler",
    SEK:	"Sum egenkapital",
    SF: 	"Sum fordringer",
    SFA:	"Sum finansielle anleggsmidler",
    SG: 	"Sum gjeld",
    SGE:	"Sum egenkapital og gjeld",
    SI: 	"Sum salgsinntekter",
    SIA:	"Sum immaterielle anleggsmidler",
    SIK:	"Sum innskutt egenkapital",
    SIV:	"Sum investeringer",
    SKG:	"Sum kortsiktig gjeld",
    SKO:	"Skattekostnad på ordinært resultat",
    SKR:	"Skattekostnad på ekstraordinært resultat",
    SLF:	"Skyldig lønn og feriepenger",
    SLG:	"Sum langsiktig gjeld",
    SOK:	"Sum opptjent egenkapital",
    SOM:	"Sum omløpsmidler",
    SOVE:	"Sum overføringer og disponeringer",
    SRF:	"Skip, rigger, fly og lignende",
    SUB:	"Aksjeutbytte",
    SUBE:	"Ekstraordinært utbytte",
    SUBT:	"Tilleggsutbytte",
    SV: 	"Sum varelager",
    SVA:	"Sum varer",
    SVD:	"Sum varige driftsmidler",
    TPF:	"Tap på fordringer",
    TR: 	"Lønnsomhet (Totalrentabilitet i %)",
    UBNKA:	"Ubenyttet kassekreditt",
    US: 	"Utsatt skatt",
    USF:	"Utsatt skattefordel",
    UTB:	"Utbytte",
    VAFI:	"Verdireduksjon andre finansielle instrumenter vurdert til virkelig verdi",
    VBI:	"Biologiske eiendeler",
    VF: 	"Varekostnad",
    VMF:	"Verdiendring markedsbaserte finansielle omløpsmidler",
    VMFO:	"Verdireduksjon markedsbaserte finansielle omløpsmidler",
    VOH:	"Varelagerets omløpshastighet",
    VØKF:	"Verdiøkning markedsbaserte finansielle omløpsmidler",
    VØKI:	"Verdiøkning andre finansielle instrumenter vurdert til virkelig verdi",
    AAK:	"Aksjer og andeler i samme konsern",
    AAM:	"Andre anleggsmidler",
    AARK:	"Årsresultat før minoritetsinteresser",
    AARS:	"Årsresultat",
}

export const economickeys = Object.keys(economicCodes)